export const D_TAGS: string[] = [
  'Deponovanje otpada u zemljište ili na zemljište',
  'Izlaganje otpada procesima u zemljištu',
  'Duboko ubrizgavanje',
  'Površinsko deponovanje ',
  'Odlaganje otpada u posebno projektovane deponije',
  'Ispuštanje u vode, osim u mora, odnosno okeane',
  'Ispuštanje u mora, odnosno okeane, uključujući utiskivanje u morsko dno',
  'Biološki tretmani koji nisu naznačeni na drugom mestu u ovoj listi, a čiji su konačni proizvodi jedinjenja ili smeše koje se odbacuju u bilo kojoj od operacija od D1 do D12',
  'Fizičko-hemijsk itretmani koji nisu naznačeni na drugom mestu u ovoj listi, a čiji su konačni proizvodi jedinjenja ili smeše koje se odbacuju u bilo kojoj od operacija od D1 do D12',
  'Spaljivanje (insineracija) na tlu',
  'Spaljivanje (insineracija) na moru',
  'Trajno skladištenje',
  'Mešanje otpada pre podvrgavanja bilo kojoj od operacija od D1 do D12',
  'Prepakovanje otpada pre podvrgavanja bil okojoj od operacija od D1 do D13',
  'Skladištenje otpada koje prethodi bilo kojoj od operacija od D1 do D14',
];
export const R_TAGS: string[] = [
  'Korišćenje otpada prvenstveno ka goriva ili drugog sredstva za proizvodnju energine',
  'Regeneracija/prerada rastvarača',
  'Recikliranje/prerada organskih materija koji se ne koriste kao rastvarači (uključujući kompostiranje i ostale procese biološke transformacije)',
  'Recikliranje/prerada metala i jedinjenja metala',
  'Recikliranje/prerada drugih neorganskih materijala',
  'Regeneracija kiselina ili baza',
  'Obnavljanje komponenata koje se koriste za smanjenje zagađenja',
  'Obnavljanje komponenata katalizatora',
  'Re-rafinacija ili drugi način ponovnog iskorišćenja otpadnog ulja',
  'Izlaganje otpada procesima u zemljištu koji imaju korist za poljoprivredu il iekološki napredak',
  'Korišćenje otpada dobijenog bilo kojom operacijom od R1 do R10',
  'Promene radi podvrgavanja otpada bilo kojoj od operacija od R1 do R11',
  'Skladištenje otpada namenjenih za bilo koju operaciju od R1 do R12 (isključujući privremeno skladištenje otpada na lokaciji njegovog nastanka) ',
];
export const H_LIST: string[] = [
  'Eksplozivan',
  'Oksidirajući',
  'Visoko zapaljiv',
  'Zapaljiv',
  'Nadražujući (iritantan)',
  'Štetan (opasan)',
  'Otrovan',
  'Karcinogen',
  'Korozivan',
  'Infektivan',
  'Toksičan za reprodukciju (teratogen)',
  'Mutagen',
  'Supstance ili otpad koji u kontaktu sa vodom, vazduhom ili u kiselini otpuštaju toksične ili veoma toksične gasove',
  'Izaziva preosetljivost',
  'Ekotoksičnost',
  'Otpad koji ima svojstvo da na svak,i način nakon odlaganja proizvede drugu supstancu npr. izluževine koja ima neku od navedenih karakteristika (H1-H14)',
];
export const Y_LIST: string[] = [
  ' anatomskih supstanci; bolnički i drugi otpad sa klinika',
  'jedinjenja koja se koriste u farmaciji, medicini i veterini',
  'sredstava za zaštitu drveta',
  'biocida i fito-farmaceutskih supstanci',
  'ostataka supstanci korišćenih kao rastvarači',
  'halogenovanih organskih supstanci koje nisu korišćene kao rastvarači isključujući inertne polimerizovane materijale',
  'mešanih soli koje sadrže cijanide',
  'mineralnih ulja ili uljnih supstanci (npr. mulj od struganja)',
  'ulje/voda, mešavina ugljovodonici/voda, emulzija',
  'supstanci koje sadrže PCB i/ili PCT (npr. dielektrici i sl.)',
  'materijala sa katranom, nastalih rafinacijom, destilacijom ili bilo kojim pirolitičkim tretmanom (npr. na dnu destilacione kolone)',
  'mastila, boja, pigmenata, farbi, lakova, firnajsa',
  'smola, lateksa, plastifikatora, lepkova/adheziva',
  'hemijskih supstanci koje potiču od istraživanja i razvoja ili nastavnim aktivnostima koje nisu identifikovane i/ili su nove i čiji efekti na čoveka i/ili životnu sredinu nisu poznati (npr. ostaci iz laboratorija i sl.)',
  'pirotehničkih i drugih eksplozivnih materijala',
  'fotografskih hemikalija i materijala za razvijanje',
  'bilo kog materijala kontaminiranog sa bilo kojim kongenerom polihlorovanih dibenzo-furana',
  'bilo kog materijala kontaminiranog sa bilo kojim kongenerom polihlorovanih dibenzo-p-dioksina',
  'životinjskih i biljnih sapuna, masti, voskova',
  'nehalogenovanih organskih supstanci koje nisu korišćene kao rastvarači',
  'neorganskih supstanci bez metala i metalnih jedinjenja',
  'pepela i/ili šljaka',
  'zemlje, peska, gline uključujući zemlju, pesak, glinu iskopanu bagerom',
  'izmešanih soli koje nisu cijanidne',
  'metalne prašine, praha',
  'potrošenih katalizatora',
  'tečnosti ili muljeva koji sadrže metale ili metalna jedinjenja',
  'ostataka od operacija kontrole zagađenja (vrećasti filteri za prašinu i dr.) osim 29, 30 i 33',
  'muljeva iz skrubera',
  'muljeva iz postrojenja za prečišćavanje vode',
  'ostataka dekarbonizacije',
  'ostataka jonoizmenjivačkih kolona',
  'kanalizacionih muljeva, netretiranih ili nepodesnih za upotrebu u poljoprivredi',
  'ostataka čišćenja rezervoara i/ili opreme',
  'kontaminirane opreme',
  'kontaminiranih rezervoara -kontejnera (ambalaža, boce za gas i dr.) čiji sadržaj uključuje jednu ili više komponenti iz Priloga 4.',
  'baterija i drugih električnih ćelija',
  'biljnih ulja',
  'materijala iz selektivnog sakupljanja otpada iz domaćinstava i koji poseduju bilo koju od karakteristika iz Priloga 5.',
  'bilo koji drugi otpad koji sadrži bilo koju komponentu iz Priloga 4. i bilo koju karakteristiku iz Priloga 5.',
];
export const C_LIST: string[] = [
  'berilijum, jedinjenja berilijuma',
  'jedinjenja vanadijuma',
  'jedinjenja hroma (VI)',
  'jedinjenja kobalta',
  'jedinjenja nikla',
  'jedinjenja bakra',
  'jedinjenja cinka',
  'arsen; jedinjenja arsena',
  'selen; jedinjenja selen',
  'jedinjenja srebra',
  'kadmijum; jedinjenja kadmijuma',
  'jedinjenja kalaja',
  'antimon; jedinjenja antimona',
  'telur; jedinjenja telura',
  'jedinjenja barijuma; isključujući barijum sulfat',
  'živu; jedinjenja žive',
  'talijum; jedinjenja talijuma',
  'olovo; jedinjenja olova',
  'neorganske sulfide',
  'neorganska jedinjenja fluora; isključujući kalcijum fluorid',
  'neorganske cijanide',
  'sledeće alkalne metale ili zemnoalkalne metale: litijum, natrijum, kalijum, kalcijum, magnezijum koji nisu u smeši',
  'rastvori kiselina ili kiseline u čvrstom obliku',
  'rastvori baza ili baze u čvrstom obliku',
  'azbest (prašinu i vlakna)',
  'fosfor; fosforna jedinjenja, isključujući fosfatne minerale',
  'metalni karbonili',
  'perokside',
  'hlorate',
  'perhlorate',
  'azide',
  'PCB i/ili PCT',
  'jedinjenja koja se koriste u farmaciji ili veterini',
  'biocide i fito-farmaceutske supstance (npr. pesticide i sl.)',
  'infektivne supstance',
  'kreozati',
  'izocijanati; tiocijanati',
  'organske cijanide (npr. nitrile i sl.)',
  'fenole; jedinjenja fenola',
  'halogenovane rastvarače',
  'organske rastvarače, isključujući halogenovane rastvarače',
  'organohalogena jedinjenja, isključujući inertne polimerizovane materije i ostale supstance navedene u ovom prilogu',
  'aromatična jedinjenja; policiklična i heterociklična organska jedinjenja',
  'alifatične amine',
  'aromatične amine',
  'etre',
  'supstance koje imaju osobine eksploziva, isključujući one koje su navedene u ovom prilogu',
  'sumporna organska jedinjenja',
  'bilo koji kongener polihlorovanih dibenzo-furana',
  'bilo koji kongener polihlorovanih dibenzo-p-dioksina',
  'ugljovodonike i kiseonik; azotna i/ili sumporna jedinjenja koja nisu uzeta u obzir u ovom prilogu',
];
export const TRASH_STATES: string[] = ['Čvrsto', 'Tečno', 'Gasovito', 'Prah'];
